import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    setupFiles: ["./src/test/setup.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: ["src/lib/**", "src/app/api/**", "src/components/**"],
      exclude: [
        "src/lib/db/seed*.ts",
        "src/lib/db/migrate.ts",
        "src/lib/db/fix-*.ts",
        "src/lib/db/add-member.ts",
        "src/lib/db/rename-portco.ts",
        "src/lib/db/remove-demo-data.ts",
        "src/lib/db/reset-demo-data.ts",
        "src/lib/db/set-*.ts",
        "src/lib/db/link-*.ts",
        "src/lib/db/create-*.ts",
        "src/lib/db/setup-*.ts",
        "src/lib/db/test-*.ts",
        "src/lib/db/migrations/**",
        "src/lib/agents/*/prompt.ts",
        "src/lib/agents/im-processor/prompt.ts",
        "src/lib/agents/im-processor/prompts/**",
        "src/components/ui/**",
        "src/lib/thesis/template.ts",
        "src/lib/db/schema/index.ts",
        "src/lib/db/cached-queries.ts",
        "src/lib/agents/im-processor/schemas/pipeline-result.ts",
        "src/lib/gdrive/error-logger.ts",
        "src/lib/agents/im-processor/index.ts",
        "src/lib/agents/im-processor/eval.ts",
        "src/lib/agents/im-processor/pipeline.ts",
        "src/lib/agents/im-processor/store-results.ts",
        "src/lib/agents/im-processor/agents/analyzer.ts",
        "src/lib/agents/dd-processor/index.ts",
        "src/lib/agents/discovery-interviewer/index.ts",
        "src/lib/agents/thesis-generator/index.ts",
        "src/lib/agents/content-extractor/index.ts",
        "src/lib/agents/external-enricher/index.ts",
        "src/lib/agents/file-classifier/pdf-renderer.ts",
      ],
      thresholds: {
        lines: 60,
        functions: 60,
        branches: 50,
      },
    },
  },
  resolve: {
    alias: { "@": path.resolve(__dirname, "./src") },
  },
});
