/**
 * Base DD thesis tree template — universal nodes that apply to every deal.
 * Industry-specific branches are generated by the thesis AI agent.
 */

export interface TemplateNode {
  id: string;
  parentId: string | null;
  label: string;
  description: string;
  sortOrder: number;
  /** Hint for the AI agent on what IM data maps to this node */
  mappingHint?: string;
}

export const BASE_TEMPLATE: TemplateNode[] = [
  // Root
  {
    id: "root",
    parentId: null,
    label: "Investment Recovery within 5 Years",
    description: "Can we recover our investment within 5 years?",
    sortOrder: 0,
  },

  // ── Level 1 ──
  {
    id: "internal",
    parentId: "root",
    label: "Internal Assessment",
    description: "Internal environment assessment",
    sortOrder: 0,
  },
  {
    id: "external",
    parentId: "root",
    label: "External Assessment",
    description: "External environment assessment",
    sortOrder: 1,
  },

  // ── Internal > Revenue ──
  {
    id: "revenue",
    parentId: "internal",
    label: "Revenue",
    description: "Revenue analysis",
    sortOrder: 0,
  },
  {
    id: "revenue_composition",
    parentId: "revenue",
    label: "Revenue Composition",
    description: "Revenue breakdown by product/service, unit price, volume",
    sortOrder: 0,
    mappingHint: "financialHighlights.revenue, financialHighlights.recurringRevenue",
  },
  {
    id: "revenue_channels",
    parentId: "revenue",
    label: "Deal Sourcing Channels",
    description: "Deal sourcing channels (direct vs. agency/referral)",
    sortOrder: 1,
    mappingHint: "rawObservations.serviceModelInfo",
  },
  {
    id: "retention",
    parentId: "revenue",
    label: "Customer Retention",
    description: "Existing customer retention and churn rates",
    sortOrder: 2,
    mappingHint: "rawObservations.clientInfo, financialHighlights.topClientConcentration",
  },
  {
    id: "revenue_per_employee",
    parentId: "revenue",
    label: "Revenue per Employee",
    description: "Revenue per employee",
    sortOrder: 3,
    mappingHint: "financialHighlights.revenue, financialHighlights.employeeCount",
  },
  {
    id: "product_profitability",
    parentId: "revenue",
    label: "Product Profitability",
    description: "Profitable vs. unprofitable product/service lines",
    sortOrder: 4,
    mappingHint: "rawObservations.serviceModelInfo",
  },
  {
    id: "customer_satisfaction",
    parentId: "revenue",
    label: "Customer Satisfaction",
    description: "Customer satisfaction metrics (surveys, churn, referrals, ROI)",
    sortOrder: 5,
    mappingHint: "rawObservations.clientInfo",
  },

  // ── Internal > Finance ──
  {
    id: "finance",
    parentId: "internal",
    label: "Financial DD",
    description: "Financial due diligence",
    sortOrder: 1,
  },
  {
    id: "costs",
    parentId: "finance",
    label: "Cost Structure",
    description: "Cost structure analysis",
    sortOrder: 0,
  },
  {
    id: "private_expenses",
    parentId: "costs",
    label: "Owner/Private Expenses",
    description: "Owner/private expenses that can be normalized",
    sortOrder: 0,
  },
  {
    id: "capex",
    parentId: "costs",
    label: "Capital Expenditure",
    description: "Capital expenditure needs and appropriateness",
    sortOrder: 1,
  },
  {
    id: "cashflow",
    parentId: "finance",
    label: "Cash Flow",
    description: "Cash flow analysis for 5-year payback",
    sortOrder: 1,
  },
  {
    id: "financial_viability",
    parentId: "cashflow",
    label: "5-Year Recovery Viability",
    description: "Financial viability of 5-year investment recovery",
    sortOrder: 0,
    mappingHint: "financialHighlights.ebitda, financialHighlights.ebitdaMargin",
  },
  {
    id: "working_capital",
    parentId: "cashflow",
    label: "Working Capital",
    description: "Working capital requirements for 5-year recovery",
    sortOrder: 1,
    mappingHint: "financialHighlights.debtLevel",
  },

  // ── Internal > Upside ──
  {
    id: "upside",
    parentId: "internal",
    label: "Upside Potential",
    description: "Growth and upside potential",
    sortOrder: 2,
  },
  {
    id: "existing_segments",
    parentId: "upside",
    label: "Existing Segments",
    description: "Growth opportunities in existing segments",
    sortOrder: 0,
    mappingHint: "rawObservations.clientInfo",
  },
  {
    id: "new_segments",
    parentId: "upside",
    label: "New Segments",
    description: "New market/segment expansion opportunities",
    sortOrder: 1,
  },

  // ── Internal > Product ──
  {
    id: "product",
    parentId: "internal",
    label: "Product & Technology",
    description: "Product and technology assessment",
    sortOrder: 3,
  },
  {
    id: "competitive_advantage",
    parentId: "product",
    label: "Competitive Advantage",
    description: "Product competitive moat and differentiation",
    sortOrder: 0,
    mappingHint: "companyProfile.marketPosition",
  },
  {
    id: "new_development",
    parentId: "product",
    label: "New Product Development",
    description: "New product development pipeline",
    sortOrder: 1,
    mappingHint: "rawObservations.technologyInfo",
  },
  {
    id: "product_eol",
    parentId: "product",
    label: "Product End-of-Life",
    description: "Existing product end-of-life risks",
    sortOrder: 2,
  },
  {
    id: "regulatory_compliance",
    parentId: "product",
    label: "Regulatory Compliance",
    description: "Product-level regulatory and compliance requirements",
    sortOrder: 3,
    mappingHint: "rawObservations.legalComplianceInfo",
  },

  // ── Internal > Organization ──
  {
    id: "organization",
    parentId: "internal",
    label: "Organization & People",
    description: "Organizational structure and people",
    sortOrder: 4,
  },
  {
    id: "human_resources",
    parentId: "organization",
    label: "Human Resources",
    description: "Workforce analysis",
    sortOrder: 0,
  },
  {
    id: "utilization",
    parentId: "human_resources",
    label: "Utilization Rate",
    description: "Employee utilization rate",
    sortOrder: 0,
    mappingHint: "rawObservations.laborPracticesInfo",
  },
  {
    id: "hiring_needs",
    parentId: "human_resources",
    label: "Hiring Needs",
    description: "Additional hiring requirements",
    sortOrder: 1,
    mappingHint: "financialHighlights.employeeCount",
  },
  {
    id: "sustainability",
    parentId: "human_resources",
    label: "Workforce Sustainability",
    description: "Workforce sustainability (overtime, tenure, attrition)",
    sortOrder: 2,
    mappingHint: "rawObservations.laborPracticesInfo, rawObservations.integrationInfo",
  },
  {
    id: "labor_cost",
    parentId: "human_resources",
    label: "Labor Costs",
    description: "Labor costs and compensation appropriateness",
    sortOrder: 3,
    mappingHint: "rawObservations.laborPracticesInfo",
  },
  {
    id: "key_people",
    parentId: "organization",
    label: "Key Person Risk",
    description: "Key person dependency and succession risk",
    sortOrder: 1,
    mappingHint: "managementTeam",
  },

  // ── Internal > Legal ──
  {
    id: "legal",
    parentId: "internal",
    label: "Legal & Compliance",
    description: "Legal, compliance, and regulatory risks",
    sortOrder: 5,
  },
  {
    id: "litigation",
    parentId: "legal",
    label: "Litigation Risk",
    description: "Pending or potential litigation",
    sortOrder: 0,
    mappingHint: "rawObservations.legalComplianceInfo",
  },
  {
    id: "contracts",
    parentId: "legal",
    label: "Contract Risk",
    description: "Key contract terms, change-of-control clauses",
    sortOrder: 1,
    mappingHint: "rawObservations.clientInfo",
  },
  {
    id: "ip_rights",
    parentId: "legal",
    label: "Intellectual Property",
    description: "IP ownership, patents, licenses",
    sortOrder: 2,
    mappingHint: "rawObservations.technologyInfo",
  },

  // ── External > Market ──
  {
    id: "market",
    parentId: "external",
    label: "Market Trends",
    description: "Market trends and dynamics",
    sortOrder: 0,
  },
  {
    id: "market_size",
    parentId: "market",
    label: "Market Size",
    description: "Total addressable market and growth trajectory",
    sortOrder: 0,
    mappingHint: "companyProfile.industryTrends",
  },
  {
    id: "target_segments",
    parentId: "market",
    label: "Target Segments",
    description: "Client target segments, budget amounts, and cycles",
    sortOrder: 1,
  },

  // ── External > Competition ──
  {
    id: "competition",
    parentId: "external",
    label: "Competitive Landscape",
    description: "Competitive landscape",
    sortOrder: 1,
  },
  {
    id: "direct_competition",
    parentId: "competition",
    label: "Direct Competitors",
    description: "Direct competitors: market share, positioning",
    sortOrder: 0,
    mappingHint: "companyProfile.marketPosition",
  },
  {
    id: "indirect_competition",
    parentId: "competition",
    label: "Indirect Competitors",
    description: "Indirect competitors and whitespace analysis",
    sortOrder: 1,
  },
];

/** Returns the base template as a flat array ready for DB insertion */
export function getBaseTemplate(): TemplateNode[] {
  return BASE_TEMPLATE;
}
